services:
  db:
    image: "postgres:17-alpine"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workmate-hub
    ports:
      - "5432:5432"
